import Hierarchy from "./Hierarchy";

export default function App() {
  return (
    <div
      style={{
        minHeight: "100vh",
        width: "100vw",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
      }}
    >
      <Hierarchy rawData={data} />
    </div>
  );
}

const data = [
  {
    id: 9,
    code: "N-B-Z02-S02-S02",
    group: "B",
    zone: "Z02",
    subzone1: "S02",
    subzone2: "S02",
    name_gujarati: "મનસુખભાઈ રામાણી",
    role_gujarati: "સંવાહક",
    full_name_gujarati: "મનસુખભાઈ રામાણી",
    reporting_to: "બિપીનભાઈ કિકાણી",
    last_name: "Ramani",
    first_name: "Manshukhbhai",
    father_name: "Ratilalbhai",
    mobile: "9879504822",
    designation_gujarati: "સમર્પિત",
    active: "Y",
  },
  {
    id: 10,
    code: "N-B-Z07-S03-S03",
    group: "B",
    zone: "Z07",
    subzone1: "S03",
    subzone2: "S03",
    name_gujarati: "નવનીતભાઈ બાબરીયા",
    role_gujarati: "સંવાહક",
    full_name_gujarati: "નવનીતભાઈ બાબરીયા",
    reporting_to: "મનસુખભાઈ નાકરાણી",
    last_name: "Babriya",
    first_name: "Navneetbhai",
    father_name: "Keshubhai",
    mobile: "9825773872",
    designation_gujarati: "આત્મીય",
    active: "Y",
  },
  {
    id: 11,
    code: "N-B-Z02-S04-S04",
    group: "B",
    zone: "Z02",
    subzone1: "S04",
    subzone2: "S04",
    name_gujarati: "અશોકભાઈ રાખોલીયા",
    role_gujarati: "સંવાહક",
    full_name_gujarati: "અશોકભાઈ રાખોલીયા",
    reporting_to: "બિપીનભાઈ કિકાણી",
    last_name: "Rakholiya",
    first_name: "Ashokbhai",
    father_name: "",
    mobile: "9925425857",
    designation_gujarati: "સેવક",
    active: "Y",
  },
  {
    id: 13,
    code: "N-B-Z11-S05-S05",
    group: "B",
    zone: "Z11",
    subzone1: "S05",
    subzone2: "S05",
    name_gujarati: "અશોકભાઈ સાંગાણી",
    role_gujarati: "સંવાહક",
    full_name_gujarati: "અશોકભાઈ સાંગાણી",
    reporting_to: "પ્રવીણભાઈ નાકરાણી",
    last_name: "Sangani",
    first_name: "Ashokbhai",
    father_name: "",
    mobile: "9898104884",
    designation_gujarati: "સેવક",
    active: "Y",
  },
  {
    id: 14,
    code: "N-B-Z09-S06-S06",
    group: "B",
    zone: "Z09",
    subzone1: "S06",
    subzone2: "S06",
    name_gujarati: "કાનજીભાઈ રફળિયા",
    role_gujarati: "સંવાહક",
    full_name_gujarati: "કાનજીભાઈ રફળિયા",
    reporting_to: "ચતુરભાઈ ચોવટીયા",
    last_name: "Rafaliya",
    first_name: "Kanjibhai",
    father_name: "",
    mobile: "9825545180",
    designation_gujarati: "સેવક",
    active: "Y",
  },
  {
    id: 17,
    code: "N-B-Z08-S07-S07",
    group: "B",
    zone: "Z08",
    subzone1: "S07",
    subzone2: "S07",
    name_gujarati: "જયદીપભાઈ અમીપરા",
    role_gujarati: "સંવાહક",
    full_name_gujarati: "જયદીપભાઈ અમીપરા",
    reporting_to: "ઉન્નડભાઈ વાઘ",
    last_name: "Amipra",
    first_name: "Jaydeepbhai",
    father_name: "",
    mobile: "9624586700",
    designation_gujarati: "સેવક",
    active: "Y",
  },
  {
    id: 21,
    code: "N-B-Z12-S08-S08",
    group: "B",
    zone: "Z12",
    subzone1: "S08",
    subzone2: "S08",
    name_gujarati: "મનીષભાઈ તળાવીયા",
    role_gujarati: "સંવાહક",
    full_name_gujarati: "મનીષભાઈ તળાવીયા",
    reporting_to: "મુકેશભાઈ બોરડ",
    last_name: "Talaviya",
    first_name: "Manishbhai",
    father_name: "",
    mobile: "9099835371",
    designation_gujarati: "સેવક",
    active: "Y",
  },
  {
    id: 22,
    code: "N-B-Z20-S09-S09",
    group: "B",
    zone: "Z20",
    subzone1: "S09",
    subzone2: "S09",
    name_gujarati: "રમેશભાઈ દેસાઈ",
    role_gujarati: "સંવાહક",
    full_name_gujarati: "રમેશભાઈ દેસાઈ",
    reporting_to: "ગીરીશભાઈ પટેલ",
    last_name: "Deshai",
    first_name: "Rameshbhai",
    father_name: "",
    mobile: "9825395917",
    designation_gujarati: "સેવક",
    active: "Y",
  },
  {
    id: 24,
    code: "N-B-Z06-S10-S10",
    group: "B",
    zone: "Z06",
    subzone1: "S10",
    subzone2: "S10",
    name_gujarati: "સંજયભાઈ ડોબરીયા",
    role_gujarati: "સંવાહક",
    full_name_gujarati: "સંજયભાઈ ડોબરીયા",
    reporting_to: "મનીષભાઈ પેથાણી",
    last_name: "Dobriya",
    first_name: "Sanjaybhai",
    father_name: "",
    mobile: "9377090013",
    designation_gujarati: "સેવક",
    active: "Y",
  },
  {
    id: 25,
    code: "N-B-Z09-S11-S11",
    group: "B",
    zone: "Z09",
    subzone1: "S11",
    subzone2: "S11",
    name_gujarati: "સંજયભાઈ સુતરીયા",
    role_gujarati: "સંવાહક",
    full_name_gujarati: "સંજયભાઈ સુતરીયા",
    reporting_to: "ચતુરભાઈ ચોવટીયા",
    last_name: "Sutariya",
    first_name: "Sanjaybhai",
    father_name: "",
    mobile: "9725686780",
    designation_gujarati: "સેવક",
    active: "Y",
  },
  {
    id: 26,
    code: "N-B-Z09-S12-S12",
    group: "B",
    zone: "Z09",
    subzone1: "S12",
    subzone2: "S12",
    name_gujarati: "કાંતિલાલ નાદપરા",
    role_gujarati: "સંવાહક",
    full_name_gujarાત: "કાંતિલાલ નાદપરા",
    reporting_to: "ચતુરભાઈ ચોવટીયા",
    last_name: "Nadpra",
    first_name: "Kantilal",
    father_name: "",
    mobile: "7433058242",
    designation_gujarાતി: "સેવક",
    active: "Y",
  },
  {
    id: 27,
    code: "N-B-Z09-S30-S30",
    group: "B",
    zone: "Z09",
    subzone1: "S30",
    subzone2: "S30",
    name_gujarati: "કિરણભાઈ રામાણી",
    role_gujarati: "સંવાહક",
    full_name_gujarાત: "કિરણભાઈ રામાણી",
    reporting_to: "ચતુરભાઈ ચोવટીયા",
    last_name: "Ramani",
    first_name: "Kiranbhai",
    father_name: "",
    mobile: "7874680765",
    designation_gujarતિ: "સેવક",
    active: "Y",
  },
  {
    id: 28,
    code: "N-B-Z10-S13-S13",
    group: "B",
    zone: "Z10",
    subzone1: "S13",
    subzone2: "S13",
    name_gujarati: "જયેશભાઇ દુધાત્રા",
    role_gujarati: "સંવાહક",
    full_name_gujarati: "જયેશભાઇ દુધાત્રા",
    reporting_to: "જગદીશભાઈ નંદવાણા",
    last_name: "Dudhatra",
    first_name: "Jayeshbhai",
    father_name: "",
    mobile: "9427820878",
    designation_gujarાતી: "સેવક",
    active: "Y",
  },
  {
    id: 29,
    code: "N-B-Z06-S14-S14",
    group: "B",
    zone: "Z06",
    subzone1: "S14",
    subzone2: "S14",
    name_gujarati: "દિવ્યેશભાઈ કકાણી",
    role_gujarati: "સંવાહક",
    full_name_gujarati: "દિવ્યેશભાઈ કકાણી",
    reporting_to: "મનીષભાઈ પેથાણી",
    last_name: "Kakani",
    first_name: "Divyeshbhai",
    father_name: "",
    mobile: "9909427253",
    designation_gujarાતી: "સેવક",
    active: "Y",
  },
  {
    id: 30,
    code: "N-B-Z14-S15-S15",
    group: "B",
    zone: "Z14",
    subzone1: "S15",
    subzone2: "S15",
    name_gujarati: "ધવલભાઈ વસાણી",
    role_gujarati: "સંવાહક",
    full_name_gujarati: "ધવલભાઈ વસાણી",
    reporting_to: "ચિરાગભાઈ વસાણી",
    last_name: "Vashani",
    first_name: "Dhavalbhai",
    father_name: "",
    mobile: "9408025436",
    designation_gujarાતી: "સેવક",
    active: "Y",
  },
  {
    id: 31,
    code: "N-B-Z11-S16-S16",
    group: "B",
    zone: "Z11",
    subzone1: "S16",
    subzone2: "S16",
    name_gujarati: "ધીરજભાઈ કણજારીયા",
    role_gujarati: "સંવાહક",
    full_name_gujarati: "ધીરજભાઈ કણજારીયા",
    reporting_to: "પ્રવીણભાઈ નાકરાણી",
    last_name: "Kanjariya",
    first_name: "Dhirajbhai",
    father_name: "",
    mobile: "9773158662",
    designation_gujarાતી: "સેવક",
    active: "Y",
  },
  {
    id: 32,
    code: "N-B-Z18-S17-S17",
    group: "B",
    zone: "Z18",
    subzone1: "S17",
    subzone2: "S17",
    name_gujarati: "પરેશભાઈ રાદડિયા",
    role_gujarati: "સંવાહક",
    full_name_gujarati: "પરેશભાઈ રાદડિયા",
    reporting_to: "વિરલભાઈ અંટાળા",
    last_name: "Raddiya",
    first_name: "Pareshbhai",
    father_name: "",
    mobile: "9879829399",
    designation_gujarાતી: "સેવક",
    active: "Y",
  },
  {
    id: 33,
    code: "N-B-Z14-S18-S18",
    group: "B",
    zone: "Z14",
    subzone1: "S18",
    subzone2: "S18",
    name_gujarati: "પ્રદીપભાઈ હપાણી",
    role_gujarati: "સંવાહક",
    full_name_gujarati: "પ્રદીપભાઈ હપાણી",
    reporting_to: "ચિરાગભાઈ વસાણી",
    last_name: "Hapani",
    first_name: "Pardipbhai",
    father_name: "Dhirubhai",
    mobile: "9979684896",
    designation_gujarાતી: "સેવક",
    active: "Y",
  },
  {
    id: 34,
    code: "N-B-Z09-S19-S19",
    group: "B",
    zone: "Z09",
    subzone1: "S19",
    subzone2: "S19",
    name_gujarati: "પ્રેમભાઈ રામાણી",
    role_gujarati: "સંવાહક",
    full_name_gujarati: "પ્રેમભાઈ રામાણી",
    reporting_to: "ચતુરભાઈ ચોવટીયા",
    last_name: "Ramani",
    first_name: "Prembhai",
    father_name: "",
    mobile: "9427716359",
    designation_gujarાતી: "સેવક",
    active: "Y",
  },
  {
    id: 36,
    code: "N-B-Z14-S20-S20",
    group: "B",
    zone: "Z14",
    subzone1: "S20",
    subzone2: "S20",
    name_gujarati: "મહેશભાઈ ભાલાળા",
    role_gujarati: "સંવાહક",
    full_name_gujarati: "મહેશભાઈ ભાલાળા",
    reporting_to: "ચિરાગભાઈ વસાણી",
    last_name: "Bhalala",
    first_name: "Maheshbhai",
    father_name: "",
    mobile: "8758523428",
    designation_gujarati: "સેવક",
    active: "Y",
  },
  {
    id: 37,
    code: "N-B-Z08-S32-S32",
    group: "B",
    zone: "Z08",
    subzone1: "S32",
    subzone2: "S32",
    name_gujarati: "મેહુલભાઈ દોંગા",
    role_gujarati: "સંવાહક",
    full_name_gujarati: "મેહુલભાઈ દોંગા",
    reporting_to: "ઉન્નડભાઈ વાઘ",
    last_name: "Dnoga",
    first_name: "Mehulbhai",
    father_name: "",
    mobile: "8140987634",
    designation_gujarતી: "સેવક",
    active: "Y",
  },
  {
    id: 40,
    code: "N-B-Z14-S22-S22",
    group: "B",
    zone: "Z14",
    subzone1: "S22",
    subzone2: "S22",
    name_gujarati: "વિપુલભાઈ સાવલિયા",
    role_gujarati: "સંવાહક",
    full_name_gujarati: "વિપુલભાઈ સાવલિયા",
    reporting_to: "ચિરાગભાઈ વસાણી",
    last_name: "Savlia",
    first_name: "Vipulbhai",
    father_name: "",
    mobile: "9712266952",
    designation_gujarતી: "સેવક",
    active: "Y",
  },
  {
    id: 41,
    code: "N-B-Z13-S23-S23",
    group: "B",
    zone: "Z13",
    subzone1: "S23",
    subzone2: "S23",
    name_gujarati: "સંદીપભાઈ ગેવરીયા",
    role_gujarati: "સંવાહક",
    full_name_gujarati: "સંદીપભાઈ ગેવરીયા",
    reporting_to: "અલ્કેશભાઈ મેતલીયા",
    last_name: "Gevriya",
    first_name: "Sandipbhai",
    father_name: "",
    mobile: "9099624722",
    designation_gujarતી: "સેવક",
    active: "Y",
  },
  {
    id: 42,
    code: "N-B-Z13-S24-S24",
    group: "B",
    zone: "Z13",
    subzone1: "S24",
    subzone2: "S24",
    name_gujarati: "સુરેશભાઈ વસોયા",
    role_gujarati: "સંવાહક",
    full_name_gujarati: "સુરેશભાઈ વસોયા",
    reporting_to: "અલ્કેશભાઈ મેતલીયા",
    last_name: "Vashoya",
    first_name: "Sureshbhai",
    father_name: "",
    mobile: "9624332220",
    designation_gujarતી: "સેવક",
    active: "Y",
  },
  {
    id: 43,
    code: "N-B-Z08-S33-S33",
    group: "B",
    zone: "Z08",
    subzone1: "S33",
    subzone2: "S33",
    name_gujarati: "જયેશભાઈ નાકરાણી",
    role_gujarati: "સંવાહક",
    full_name_gujarati: "જયેશભાઈ નાકરાણી",
    reporting_to: "ઉન્નડભાઈ વાઘ",
    last_name: "Nakrani",
    first_name: "Jayeshbhai",
    father_name: "",
    mobile: "9978205586",
    designation_gujarતી: "સેવક",
    active: "Y",
  },
  {
    id: 44,
    code: "N-B-Z17-S25-S25",
    group: "B",
    zone: "Z17",
    subzone1: "S25",
    subzone2: "S25",
    name_gujarati: "ઘનશ્યામભાઈ પારેજીયા",
    role_gujarati: "સંવાહક",
    full_name_gujarati: "ઘનશ્યામભાઈ પારેજીયા",
    reporting_to: "મહેશભાઈ પટેલ",
    last_name: "Parejiya",
    first_name: "Ghanshyambhai",
    father_name: "Govindbhai",
    mobile: "9408574736",
    designation_gujarતી: "સમર્પિત",
    active: "Y",
  },
  {
    id: 46,
    code: "N-B-Z14-S31-S31",
    group: "B",
    zone: "Z14",
    subzone1: "S31",
    subzone2: "S31",
    name_gujarati: "મયુરભાઈ લિબમ્ડ",
    role_gujarati: "સંવાહક",
    full_name_gujarati: "મયુરભાઈ લિબમ્ડ",
    reporting_to: "ચિરાગભાઈ વસાણી",
    last_name: "Limbd",
    first_name: "Mayurbhai",
    father_name: "Prfulbhai",
    mobile: "7284023879",
    designation_gujarતી: "",
    active: "Y",
  },
  {
    id: 50,
    code: "N-B-Z19-V02-V02",
    group: "B",
    zone: "Z19",
    subzone1: "V02",
    subzone2: "V02",
    name_gujarati: "ડાયાભાઈ કચ્છી",
    role_gujarati: "વાહક",
    full_name_gujarati: "ડાયાભાઈ કચ્છી",
    reporting_to: "ત્રિકમભાઈ ગજેરા",
    last_name: "Kachhi",
    first_name: "Dayabhai",
    father_name: "Sanbhubhai",
    mobile: "9979998277",
    designation_gujarતી: "સમર્પિત",
    active: "Y",
  },
  {
    id: 53,
    code: "N-B-Z19-V03-V03",
    group: "B",
    zone: "Z19",
    subzone1: "V03",
    subzone2: "V03",
    name_gujarati: "જીવરાજભાઈ સુદાણી",
    role_gujarati: "વાહક",
    full_name_gujarati: "જીવરાજભાઈ સુદાણી",
    reporting_to: "ત્રિકમભાઈ ગજેરા",
    last_name: "Sudani",
    first_name: "Jivrajbhai",
    father_name: "Manjibhai",
    mobile: "9825066593",
    designation_gujarતી: "આત્મીય",
    active: "Y",
  },
  {
    id: 55,
    code: "N-B-Z19-V04-V04",
    group: "B",
    zone: "Z19",
    subzone1: "V04",
    subzone2: "V04",
    name_gujarati: "પરશોતમભાઈ ધોરાજીયા",
    role_gujarati: "વાહક",
    full_name_gujarati: "પરશોતમભાઈ ધોરાજીયા",
    reporting_to: "ત્રિકમભાઈ ગજેરા",
    last_name: "Dhorajiya",
    first_name: "Parshotambhai",
    father_name: "Keshubhai",
    mobile: "9925233137",
    designation_gujarતી: "આત્મીય",
    active: "Y",
  },
  {
    id: 56,
    code: "N-B-Z02-V05-V05",
    group: "B",
    zone: "Z02",
    subzone1: "V05",
    subzone2: "V05",
    name_gujarati: "ભાવેશભાઈ પેથાણી",
    role_gujarati: "વાહક",
    full_name_gujarati: "ભાવેશભાઈ પેથાણી",
    reporting_to: "બિપીનભાઈ કિકાણી",
    last_name: "Pethani",
    first_name: "Bhaveshbhai",
    father_name: "",
    mobile: "9879514483",
    designation_gujarતી: "આત્મીય",
    active: "Y",
  },
  {
    id: 59,
    code: "N-B-Z07-V06-V06",
    group: "B",
    zone: "Z07",
    subzone1: "V06",
    subzone2: "V06",
    name_gujarati: "ગોવિંદભાઈ ખોખાણી",
    role_gujarati: "વાહક",
    full_name_gujarati: "ગોવિંદભાઈ ખોખાણી",
    reporting_to: "મનસુખભાઈ નાકરાણી",
    last_name: "Khokhni",
    first_name: "Govindbhai",
    father_name: "Talshibhai",
    mobile: "9979872251",
    designation_gujarતી: "આત્મીય",
    active: "Y",
  },
  {
    id: 60,
    code: "N-B-Z03-V07-V07",
    group: "B",
    zone: "Z03",
    subzone1: "V07",
    subzone2: "V07",
    name_gujarati: "ડૉ.મિલન ગોદાણી",
    role_gujarati: "વાહક",
    full_name_gujarati: "ડૉ.મિલન ગોદાણી",
    reporting_to: "પિયુષભાઈ પાનસુરીયા",
    last_name: "Godani",
    first_name: "Milanbhai",
    father_name: "Ghanshyambhai",
    mobile: "7990326089",
    designation_gujarતી: "આત્મીય",
    active: "Y",
  },
  {
    id: 61,
    code: "N-B-Z07-V08-V08",
    group: "B",
    zone: "Z07",
    subzone1: "V08",
    subzone2: "V08",
    name_gujarati: "અંબાલાલ ઢેબરિયા",
    role_gujarati: "વાહક",
    full_name_gujarati: "અંબાલાલ ઢેબરિયા",
    reporting_to: "મનસુખભાઈ નાકરાણી",
    last_name: "Dhebriya",
    first_name: "Ambalal",
    father_name: "Goganbhai",
    mobile: "9998219648",
    designation_gujarતી: "સુહૃદ",
    active: "Y",
  },
  {
    id: 65,
    code: "N-B-Z06-V09-V09",
    group: "B",
    zone: "Z06",
    subzone1: "V09",
    subzone2: "V09",
    name_gujarati: "અભયભાઈ રામાણી",
    role_gujarati: "વાહક",
    full_name_gujarati: "અભયભાઈ રામાણી",
    reporting_to: "મનીષભાઈ પેથાણી",
    last_name: "Ramani",
    first_name: "Abhaybhai",
    father_name: "",
    mobile: "9714344433",
    designation_gujarતી: "સેવક",
    active: "Y",
  },
  {
    id: 68,
    code: "N-B-Z02-V10-V10",
    group: "B",
    zone: "Z02",
    subzone1: "V10",
    subzone2: "V10",
    name_gujarati: "કૌશિકભાઈ ગજેરા",
    role_gujarati: "વાહક",
    full_name_gujarati: "કૌશિકભાઈ ગજેરા",
    reporting_to: "બિપીનભાઈ કિકાણી",
    last_name: "Gajera",
    first_name: "Kaushikbhai",
    father_name: "",
    mobile: "9512140848",
    designation_gujarતી: "સેવક",
    active: "Y",
  },
  {
    id: 73,
    code: "N-B-Z07-V11-V11",
    group: "B",
    zone: "Z07",
    subzone1: "V11",
    subzone2: "V11",
    name_gujarati: "દિશાંતભાઈ ઢેબરિયા",
    role_gujarati: "વાહક",
    full_name_gujarati: "દિશાંતભાઈ ઢેબરિયા",
    reporting_to: "મનસુખભાઈ નાકરાણી",
    last_name: "Debriya",
    first_name: "Dishantbhai",
    father_name: "",
    mobile: "8511934100",
    designation_gujarતી: "સેવક",
    active: "Y",
  },
  {
    id: 74,
    code: "N-B-Z10-V12-V12",
    group: "B",
    zone: "Z10",
    subzone1: "V12",
    subzone2: "V12",
    name_gujarati: "ધ્રુવેશભાઈ કસવાળા",
    role_gujarati: "વાહક",
    full_name_gujarati: "ધ્રુવેશભાઈ કસવાળા",
    reporting_to: "જગદીશભાઈ નંદવાણા",
    last_name: "Kasvala",
    first_name: "Dhuveshbhai",
    father_name: "",
    mobile: "9913945122",
    designation_gujarતી: "સેવક",
    active: "Y",
  },
  {
    id: 77,
    code: "N-B-Z10-V13-V13",
    group: "B",
    zone: "Z10",
    subzone1: "V13",
    subzone2: "V13",
    name_gujarati: "ભાવેશભાઈ સાવલિયા",
    role_gujarati: "વાહક",
    full_name_gujarati: "ભાવેશભાઈ સાવલિયા",
    reporting_to: "જગદીશભાઈ નંદવાણા",
    last_name: "Savliya",
    first_name: "Bhaveshbhai",
    father_name: "",
    mobile: "6356801676",
    designation_gujarાતી: "સેવક",
    active: "Y",
  },
  {
    id: 79,
    code: "N-B-Z16-V14-V14",
    group: "B",
    zone: "Z16",
    subzone1: "V14",
    subzone2: "V14",
    name_gujarati: "યોગેશભાઈ સોરઠીયા",
    role_gujarati: "વાહક",
    full_name_gujarati: "યોગેશભાઈ સોરઠીયા",
    reporting_to: "સતિષભાઈ નસીત",
    last_name: "Sorthiya",
    first_name: "Yogeshbhai",
    father_name: "",
    mobile: "9723232309",
    designation_gujarાતી: "સેવક",
    active: "Y",
  },
  {
    id: 83,
    code: "N-B-Z11-V15-V15",
    group: "B",
    zone: "Z11",
    subzone1: "V15",
    subzone2: "V15",
    name_gujarati: "કેયુરભાઈ માલાણી",
    role_gujarati: "વાહક",
    full_name_gujarati: "કેયુરભાઈ માલાણી",
    reporting_to: "પ્રવીણભાઈ નાકરાણી",
    last_name: "Malani",
    first_name: "Keyurbhai",
    father_name: "",
    mobile: "9408144709",
    designation_gujarાતી: "સેવક",
    active: "Y",
  },
  {
    id: 84,
    code: "N-B-Z19-V16-V16",
    group: "B",
    zone: "Z19",
    subzone1: "V16",
    subzone2: "V16",
    name_gujarati: "કનુભાઈ ગામી",
    role_gujarati: "વાહક",
    full_name_gujarati: "કનુભાઈ ગામી",
    reporting_to: "ત્રિકમભાઈ ગજેરા",
    last_name: "Gami",
    first_name: "Kanubhai",
    father_name: "",
    mobile: "9428798631",
    designation_gujarાતી: "સેવક",
    active: "Y",
  },
  {
    id: 85,
    code: "N-B-Z13-V17-V17",
    group: "B",
    zone: "Z13",
    subzone1: "V17",
    subzone2: "V17",
    name_gujarati: "નિરવભાઈ ભોજાણી",
    role_gujarati: "વાહક",
    full_name_gujarati: "નિરવભાઈ ભોજાણી",
    reporting_to: "અલ્કેશભાઈ મેતલીયા",
    last_name: "Bhojani",
    first_name: "Niravbhai",
    father_name: "",
    mobile: "7878118585",
    designation_gujarાતી: "સેવક",
    active: "Y",
  },
  {
    id: 86,
    code: "N-B-Z02-V34-V34",
    group: "B",
    zone: "Z02",
    subzone1: "V34",
    subzone2: "V34",
    name_gujarati: "પરિમલભાઈ સોલંકી",
    role_gujarati: "વાહક",
    full_name_gujarati: "પરિમલભાઈ સોલંકી",
    reporting_to: "બિપીનભાઈ કિકાણી",
    last_name: "Solanki",
    first_name: "Parimalbhai",
    father_name: "",
    mobile: "7405756309",
    designation_gujarાતી: "સેવક",
    active: "Y",
  },
  {
    id: 87,
    code: "N-B-Z16-V18-V18",
    group: "B",
    zone: "Z16",
    subzone1: "V18",
    subzone2: "V18",
    name_gujarati: "પિયુષભાઈ બાળધા",
    role_gujarati: "વાહક",
    full_name_gujarati: "પિયુષભાઈ બાળધા",
    reporting_to: "સતિષભાઈ નસીત",
    last_name: "Baldha",
    first_name: "Piyushbhai",
    father_name: "",
    mobile: "8128931828",
    designation_gujarાતી: "સેવક",
    active: "Y",
  },
  {
    id: 88,
    code: "N-B-Z09-V19-V19",
    group: "B",
    zone: "Z09",
    subzone1: "V19",
    subzone2: "V19",
    name_gujarati: "બટુકભાઈ પટોળીયા",
    role_gujarati: "વાહક",
    full_name_gujarati: "બટુકભાઈ પટોળીયા",
    reporting_to: "ચતુરભાઈ ચોવટીયા",
    last_name: "Patoliya",
    first_name: "Batukbhai",
    father_name: "",
    mobile: "9624501807",
    designation_gujarાતી: "સેવક",
    active: "Y",
  },
  {
    id: 89,
    code: "N-B-Z13-V20-V20",
    group: "B",
    zone: "Z13",
    subzone1: "V20",
    subzone2: "V20",
    name_gujarati: "બુટેશભાઈ પાધરા",
    role_gujarati: "વાહક",
    full_name_gujarati: "બુટેશભાઈ પાધરા",
    reporting_to: "અલ્કેશભાઈ મેતલીયા",
    last_name: "Padhara",
    first_name: "Buteshbhai",
    father_name: "",
    mobile: "9687372896",
    designation_gujarાતી: "સેવક",
    active: "Y",
  },
  {
    id: 90,
    code: "N-B-Z09-V22-V22",
    group: "B",
    zone: "Z09",
    subzone1: "V22",
    subzone2: "V22",
    name_gujarati: "સંજયભાઈ દેવાણી",
    role_gujarati: "વાહક",
    full_name_gujarati: "સંજયભાઈ દેવાણી",
    reporting_to: "ચતુરભાઈ ચોવટીયા",
    last_name: "Devani",
    first_name: "Sanjaybhai",
    father_name: "",
    mobile: "9825468391",
    designation_gujarાતી: "સેવક",
    active: "Y",
  },
  {
    id: 91,
    code: "N-B-Z08-V23-V23",
    group: "B",
    zone: "Z08",
    subzone1: "V23",
    subzone2: "V23",
    name_gujarati: "સ્મિતભાઈ કોટડીયા",
    role_gujarati: "વાહક",
    full_name_gujarati: "સ્મિતભાઈ કોટડીયા",
    reporting_to: "ઉન્નડભાઈ વાઘ",
    last_name: "Kotadiya",
    first_name: "Smitbhai",
    father_name: "",
    mobile: "7984830863",
    designation_gujarાતી: "સેવક",
    active: "Y",
  },
  {
    id: 93,
    code: "N-B-Z11-V24-V24",
    group: "B",
    zone: "Z11",
    subzone1: "V24",
    subzone2: "V24",
    name_gujarati: "શૈલેષભાઈ પટેલ",
    role_gujarati: "વાહક",
    full_name_gujarati: "શૈલેષભાઈ પટેલ",
    reporting_to: "પ્રવીણભાઈ નાકરાણી",
    last_name: "Patel",
    first_name: "Sileshbhai",
    father_name: "",
    mobile: "8511137644",
    designation_gujarati: "સેવક",
    active: "Y",
  },
  {
    id: 99,
    code: "N-B-Z12-V25-V25",
    group: "B",
    zone: "Z12",
    subzone1: "V25",
    subzone2: "V25",
    name_gujarati: "સુરેન્દ્રસિંહ પુવાર",
    role_gujarati: "વાહક",
    full_name_gujarati: "સુરેન્દ્રસિંહ પુવાર",
    reporting_to: "મુકેશભાઈ બોરડ",
    last_name: "Puvar",
    first_name: "Surendrasinh",
    father_name: "Nathusinh",
    mobile: "9825763432",
    designation_gujarati: "",
    active: "Y",
  },
  {
    id: 102,
    code: "N-B-Z02-Z02-Z02",
    group: "B",
    zone: "Z02",
    subzone1: "Z02",
    subzone2: "Z02",
    name_gujarati: "બિપીનભાઈ કિકાણી",
    role_gujarati: "સર સંવાહક",
    full_name_gujarati: "બિપીનભાઈ કિકાણી",
    reporting_to: "બિપીનભાઈ કિકાણી",
    last_name: "Kikani",
    first_name: "Bipinbhai",
    father_name: "Balubhai",
    mobile: "9925204262",
    designation_gujarati: "સમર્પિત",
    active: "Y",
  },
  {
    id: 107,
    code: "N-B-Z03-Z03-Z03",
    group: "B",
    zone: "Z03",
    subzone1: "Z03",
    subzone2: "Z03",
    name_gujarati: "પિયુષભાઈ પાનસુરીયા",
    role_gujarati: "સર સંવાહક",
    full_name_gujarati: "પિયુષભાઈ પાનસુરીયા",
    reporting_to: "પિયુષભાઈ પાનસુરીયા",
    last_name: "Pansuriya",
    first_name: "Piyushbhai",
    father_name: "Vallbhabhai",
    mobile: "9099993599",
    designation_gujarતી: "સમર્પિત",
    active: "Y",
  },
  {
    id: 108,
    code: "N-B-Z04-Z04-Z04",
    group: "B",
    zone: "Z04",
    subzone1: "Z04",
    subzone2: "Z04",
    name_gujarati: "નરેદ્રભાઈ પટેલ",
    role_gujarati: "સર સંવાહક",
    full_name_gujarati: "નરેદ્રભાઈ પટેલ",
    reporting_to: "નરેદ્રભાઈ પટેલ",
    last_name: "Patel",
    first_name: "Narendrabhai",
    father_name: "Atmarambhai",
    mobile: "9898713981",
    designation_gujarતી: "સમર્પિત",
    active: "Y",
  },
  {
    id: 109,
    code: "N-B-Z05-Z05-Z05",
    group: "B",
    zone: "Z05",
    subzone1: "Z05",
    subzone2: "Z05",
    name_gujarati: "બટુકભાઈ રાદડીયા",
    role_gujarati: "સર સંવાહક",
    full_name_gujarati: "બટુકભાઈ રાદડીયા",
    reporting_to: "બટુકભાઈ રાદડીયા",
    last_name: "Raddiya",
    first_name: "Bakutbhai",
    father_name: "Thakrshibhai",
    mobile: "9825061351",
    designation_gujarતી: "સમર્પિત",
    active: "Y",
  },
  {
    id: 110,
    code: "N-B-Z06-Z06-Z06",
    group: "B",
    zone: "Z06",
    subzone1: "Z06",
    subzone2: "Z06",
    name_gujarati: "મનીષભાઈ પેથાણી",
    role_gujarati: "સર સંવાહક",
    full_name_gujarati: "મનીષભાઈ પેથાણી",
    reporting_to: "મનીષભાઈ પેથાણી",
    last_name: "Pethani",
    first_name: "Manishbhai",
    father_name: "Bhikhabhai",
    mobile: "9428759077",
    designation_gujarતી: "સમર્પિત",
    active: "Y",
  },
  {
    id: 112,
    code: "N-B-Z07-Z07-Z07",
    group: "B",
    zone: "Z07",
    subzone1: "Z07",
    subzone2: "Z07",
    name_gujarati: "મનસુખભાઈ નાકરાણી",
    role_gujarati: "સર સંવાહક",
    full_name_gujarati: "મનસુખભાઈ નાકરાણી",
    reporting_to: "મનસુખભાઈ નાકરાણી",
    last_name: "Nakrani",
    first_name: "Manshukhbhai",
    father_name: "Kanjibhai",
    mobile: "9925233148",
    designation_gujarતી: "સમર્પિત",
    active: "Y",
  },
  {
    id: 115,
    code: "N-B-Z08-Z08-Z08",
    group: "B",
    zone: "Z08",
    subzone1: "Z08",
    subzone2: "Z08",
    name_gujarati: "ઉન્નડભાઈ વાઘ",
    role_gujarati: "સર સંવાહક",
    full_name_gujarati: "ઉન્નડભાઈ વાઘ",
    reporting_to: "ઉન્નડભાઈ વાઘ",
    last_name: "Vagh",
    first_name: "Unnadbhai",
    father_name: "",
    mobile: "9426038858",
    designation_gujarતી: "સેવક",
    active: "Y",
  },
  {
    id: 116,
    code: "N-B-Z09-Z09-Z09",
    group: "B",
    zone: "Z09",
    subzone1: "Z09",
    subzone2: "Z09",
    name_gujarati: "ચતુરભાઈ ચોવટીયા",
    role_gujarati: "સર સંવાહક",
    full_name_gujarati: "ચતુરભાઈ ચોવટીયા",
    reporting_to: "ચતુરભાઈ ચોવટીયા",
    last_name: "Chovtiya",
    first_name: "Chaturbhai",
    father_name: "",
    mobile: "9924152617",
    designation_gujarતી: "સેવક",
    active: "Y",
  },
  {
    id: 117,
    code: "N-B-Z10-Z10-Z10",
    group: "B",
    zone: "Z10",
    subzone1: "Z10",
    subzone2: "Z10",
    name_gujarati: "જગદીશભાઈ નંદવાણા",
    role_gujarati: "સર સંવાહક",
    full_name_gujarati: "જગદીશભાઈ નંદવાણા",
    reporting_to: "જગદીશભાઈ નંદવાણા",
    last_name: "Nandvana",
    first_name: "Jagdeeshbhai",
    father_name: "",
    mobile: "9277759567",
    designation_gujarતી: "સેવક",
    active: "Y",
  },
  {
    id: 118,
    code: "N-B-Z11-Z11-Z11",
    group: "B",
    zone: "Z11",
    subzone1: "Z11",
    subzone2: "Z11",
    name_gujarati: "પ્રવીણભાઈ નાકરાણી",
    role_gujarati: "સર સંવાહક",
    full_name_gujarati: "પ્રવીણભાઈ નાકરાણી",
    reporting_to: "પ્રવીણભાઈ નાકરાણી",
    last_name: "Nakrani",
    first_name: "Prvinbhai",
    father_name: "",
    mobile: "9925233138",
    designation_gujarતી: "સેવક",
    active: "Y",
  },
  {
    id: 119,
    code: "N-B-Z12-Z12-Z12",
    group: "B",
    zone: "Z12",
    subzone1: "Z12",
    subzone2: "Z12",
    name_gujarati: "મુકેશભાઈ બોરડ",
    role_gujarati: "સર સંવાહક",
    full_name_gujarati: "મુકેશભાઈ બોરડ",
    reporting_to: "મુકેશભાઈ બોરડ",
    last_name: "Borad",
    first_name: "Mukeshbhai",
    father_name: "",
    mobile: "9925010378",
    designation_gujarતી: "સેવક",
    active: "Y",
  },
  {
    id: 121,
    code: "N-B-Z13-Z13-Z13",
    group: "B",
    zone: "Z13",
    subzone1: "Z13",
    subzone2: "Z13",
    name_gujarati: "અલ્કેશભાઈ મેતલીયા",
    role_gujarati: "સર સંવાહક",
    full_name_gujarati: "અલ્કેશભાઈ મેતલીયા",
    reporting_to: "અલ્કેશભાઈ મેતલીયા",
    last_name: "Metliya",
    first_name: "Alkeshbhai",
    father_name: "",
    mobile: "9375201737",
    designation_gujarતી: "સેવક",
    active: "Y",
  },
  {
    id: 122,
    code: "N-B-Z14-Z14-Z14",
    group: "B",
    zone: "Z14",
    subzone1: "Z14",
    subzone2: "Z14",
    name_gujarati: "ચિરાગભાઈ વસાણી",
    role_gujarati: "સર સંવાહક",
    full_name_gujarati: "ચિરાગભાઈ વસાણી",
    reporting_to: "ચિરાગભાઈ વસાણી",
    last_name: "Vashani",
    first_name: "Chiragbhai",
    father_name: "",
    mobile: "9428846688",
    designation_gujarતી: "સેવક",
    active: "Y",
  },
  {
    id: 124,
    code: "N-B-Z16-Z16-Z16",
    group: "B",
    zone: "Z16",
    subzone1: "Z16",
    subzone2: "Z16",
    name_gujarati: "સતિષભાઈ નસીત",
    role_gujarati: "સર સંવાહક",
    full_name_gujarati: "સતિષભાઈ નસીત",
    reporting_to: "સતિષભાઈ નસીત",
    last_name: "Nashit",
    first_name: "Satishbhai",
    father_name: "",
    mobile: "9974093525",
    designation_gujarતી: "સેવક",
    active: "Y",
  },
  {
    id: 125,
    code: "N-B-Z17-Z17-Z17",
    group: "B",
    zone: "Z17",
    subzone1: "Z17",
    subzone2: "Z17",
    name_gujarati: "મહેશભાઈ પટેલ",
    role_gujarati: "સર સંવાહક",
    full_name_gujarati: "મહેશભાઈ પટેલ",
    reporting_to: "મહેશભાઈ પટેલ",
    last_name: "Patel",
    first_name: "Maheshbhai",
    father_name: "Maganbhai",
    mobile: "9898417070",
    designation_gujarતી: "આત્મીય",
    active: "Y",
  },
  {
    id: 126,
    code: "N-B-Z18-Z18-Z18",
    group: "B",
    zone: "Z18",
    subzone1: "Z18",
    subzone2: "Z18",
    name_gujarati: "વિરલભાઈ અંટાળા",
    role_gujarati: "સર સંવાહક",
    full_name_gujarati: "વિરલભાઈ અંટાળા",
    reporting_to: "વિરલભાઈ અંટાળા",
    last_name: "Antala",
    first_name: "Viralbhai",
    father_name: "Mansukhbhai",
    mobile: "8866562609",
    designation_gujarતી: "સમર્પિત",
    active: "Y",
  },
  {
    id: 127,
    code: "N-B-Z19-Z19-Z19",
    group: "B",
    zone: "Z19",
    subzone1: "Z19",
    subzone2: "Z19",
    name_gujarati: "ત્રિકમભાઈ ગજેરા",
    role_gujarati: "સર સંવાહક",
    full_name_gujarati: "ત્રિકમભાઈ ગજેરા",
    reporting_to: "ત્રિકમભાઈ ગજેરા",
    last_name: "Gajera",
    first_name: "Trikambhai",
    father_name: "Ravjibhai",
    mobile: "9925204264",
    designation_gujarતી: "સમર્પિત",
    active: "Y",
  },
  {
    id: 128,
    code: "N-B-Z20-Z20-Z20",
    group: "B",
    zone: "Z20",
    subzone1: "Z20",
    subzone2: "Z20",
    name_gujarati: "ગીરીશભાઈ પટેલ",
    role_gujarati: "સર સંવાહક",
    full_name_gujarati: "ગીરીશભાઈ પટેલ",
    reporting_to: "ગીરીશભાઈ પટેલ",
    last_name: "Patel",
    first_name: "Girishbhai",
    father_name: "",
    mobile: "9173909454",
    designation_gujarતી: "સેવક",
    active: "Y",
  },
  {
    id: 164,
    code: "N-B-Z06-V26-V26",
    group: "B",
    zone: "Z06",
    subzone1: "V26",
    subzone2: "V26",
    name_gujarati: "તરૂણભાઈ તારપરા",
    role_gujarati: "વાહક",
    full_name_gujarati: "તરૂણભાઈ તારપરા",
    reporting_to: "મનીષભાઈ પેથાણી",
    last_name: "Tarpra",
    first_name: "Trunbhai",
    father_name: "Kantibhai",
    mobile: "9727000558",
    designation_gujarati: "",
    active: "Y",
  },
  {
    id: 167,
    code: "N-B-Z05-V29-V29",
    group: "B",
    zone: "Z05",
    subzone1: "V29",
    subzone2: "V29",
    name_gujarati: "પ્રાગજીભાઈ કથીરીયા",
    role_gujarતિ: "વાહક",
    full_name_gujarતિ: "પ્રાગજીભાઈ કથીરીયા",
    reporting_to: "બટુકભાઈ રાદડીયા",
    last_name: "Kathiriya",
    first_name: "Pragjibhai",
    father_name: "Madhubhai",
    mobile: "9824572122",
    designation_gujarતિ: "",
    active: "Y",
  },
  {
    id: 186,
    code: "N-B-Z09-V30-V30",
    group: "B",
    zone: "Z09",
    subzone1: "V30",
    subzone2: "V30",
    name_gujarati: "ઉત્સવભાઈ રામાણી",
    role_gujarati: "વાહક",
    full_name_gujarati: "ઉત્સવભાઈ રામાણી",
    reporting_to: "ચતુરભાઈ ચોવટીયા",
    last_name: "Ramani",
    first_name: "Utsavbhai",
    father_name: "Kiritbhai",
    mobile: "8758656160",
    designation_gujarati: "",
    active: "Y",
  },
  {
    id: 198,
    code: "N-B-Z10-S26-S26",
    group: "B",
    zone: "Z10",
    subzone1: "S26",
    subzone2: "S26",
    name_gujarati: "પરેશભાઈ ટાઢાણી",
    role_gujarati: "સંવાહક",
    full_name_gujarati: "પરેશભાઈ ટાઢાણી",
    reporting_to: "જગદીશભાઈ નંદવાણા",
    last_name: "Tadhani",
    first_name: "Pareshbhai",
    father_name: "Tulshibhai",
    mobile: "9228286102",
    designation_gujarતી: "",
    active: "Y",
  },
  {
    id: 225,
    code: "N-B-Z05-V31-V31",
    group: "B",
    zone: "Z05",
    subzone1: "V31",
    subzone2: "V31",
    name_gujarati: "શૈલેષભાઈ રોકડ",
    role_gujarati: "વાહક",
    full_name_gujarati: "શૈલેષભાઈ રોકડ",
    reporting_to: "બટુકભાઈ રાદડીયા",
    last_name: "Rokad",
    first_name: "Shileshbhai",
    father_name: "Haribhai",
    mobile: "9825985630",
    designation_gujarતી: "",
    active: "Y",
  },
  {
    id: 239,
    code: "N-B-Z10-S69-S69",
    group: "B",
    zone: "Z10",
    subzone1: "S69",
    subzone2: "S69",
    name_gujarati: "નીતિનકુમાર પટેલ",
    role_gujarati: "સંવાહક",
    full_name_gujarati: "નીતિનકુમાર પટેલ",
    reporting_to: "જગદીશભાઈ નંદવાણા",
    last_name: "Patel",
    first_name: "Nitinkumar",
    father_name: "Jerambhai",
    mobile: "9725166850",
    designation_gujarતી: "",
    active: "Y",
  },
  {
    id: 244,
    code: "N-B-Z16-V27-V27",
    group: "B",
    zone: "Z16",
    subzone1: "V27",
    subzone2: "V27",
    name_gujarati: "રાકેશભાઈ રૂપાવટીયા",
    role_gujarati: "વાહક",
    full_name_gujarati: "રાકેશભાઈ રૂપાવટીયા",
    reporting_to: "સતિષભાઈ નસીત",
    last_name: "Rupavtiya",
    first_name: "Rakeshbhai",
    father_name: "Himatbhai",
    mobile: "9510625312",
    designation_gujarતી: "",
    active: "Y",
  },

  {
    id: 417,
    code: "N-B-Z18-S27-S27",
    group: "B",
    zone: "Z18",
    subzone1: "S27",
    subzone2: "S27",
    name_gujarati: "પ્રતિકભાઈ ભુવા",
    role_gujarati: "સંવાહક",
    full_name_gujarati: "પ્રતિકભાઈ ભુવા",
    reporting_to: "વિરલભાઈ અંટાળા",
    last_name: "Bhuva",
    first_name: "Prtikbhai",
    father_name: "Kanubhai",
    mobile: "9023990861",
    designation_gujarati: "",
    active: "Y",
  },
  {
    id: 418,
    code: "N-B-Z09-S28-S28",
    group: "B",
    zone: "Z09",
    subzone1: "S28",
    subzone2: "S28",
    name_gujarati: "ડૉ.નિસર્ગભાઈ ચોવટિયા",
    role_gujarati: "સંવાહક",
    full_name_gujarati: "ડૉ.નિસર્ગભાઈ ચોવટિયા",
    reporting_to: "ચતુરભાઈ ચોવટીયા",
    last_name: "Chovtiya",
    first_name: "Nishrgbhai",
    father_name: "Pragjibhai",
    mobile: "8200446575",
    designation_gujarતી: "",
    active: "Y",
  },
  {
    id: 437,
    code: "N-B-Z16-S29-S29",
    group: "B",
    zone: "Z16",
    subzone1: "S29",
    subzone2: "S29",
    name_gujarati: "દર્શનભાઈ ઢોલા",
    role_gujarati: "સંવાહક",
    full_name_gujarati: "દર્શનભાઈ ઢોલા",
    reporting_to: "સતિષભાઈ નસીત",
    last_name: "Dhola",
    first_name: "Darshnabhai",
    father_name: "Babubhai",
    mobile: "8347838900",
    designation_gujarતી: "",
    active: "Y",
  },
  {
    id: 461,
    code: "N-B-Z18-V35-V35",
    group: "B",
    zone: "Z18",
    subzone1: "V35",
    subzone2: "V35",
    name_gujarati: "ધીરુભાઈ અંટાળા",
    role_gujarati: "વાહક",
    full_name_gujarati: "ધીરુભાઈ અંટાળા",
    reporting_to: "વિરલભાઈ અંટાળા",
    last_name: "Antala",
    first_name: "Dhirubhai",
    father_name: "Gokalbhai",
    mobile: "9898374198",
    designation_gujarતી: "",
    active: "Y",
  },
  {
    id: 470,
    code: "N-B-Z20-V36-V36",
    group: "B",
    zone: "Z20",
    subzone1: "V36",
    subzone2: "V36",
    name_gujarati: "કિકાણી હિતેશભાઈ",
    role_gujarati: "વાહક",
    full_name_gujarati: "કિકાણી હિતેશભાઈ",
    reporting_to: "ગીરીશભાઈ પટેલ",
    last_name: "Kikani",
    first_name: "Hiteshbhai",
    father_name: "Pravinbhai",
    mobile: "9824354867",
    designation_gujarતી: "",
    active: "Y",
  },
  {
    id: 473,
    code: "N-B-Z16-V37-V37",
    group: "B",
    zone: "Z16",
    subzone1: "V37",
    subzone2: "V37",
    name_gujarati: "મિલાપભાઈ વાજા",
    role_gujarati: "વાહક",
    full_name_gujarati: "મિલાપભાઈ વાજા",
    reporting_to: "સતિષભાઈ નસીત",
    last_name: "Waja",
    first_name: "Milapbhai",
    father_name: "Velajibhai",
    mobile: "9724582662",
    designation_gujarતી: "",
    active: "Y",
  },
  {
    id: 603,
    code: "N-B-Z05-V33-V33",
    group: "B",
    zone: "Z05",
    subzone1: "V33",
    subzone2: "V33",
    name_gujarati: "ચંદ્રેશભાઈ રોકડ",
    role_gujarati: "વાહક",
    full_name_gujarati: "ચંદ્રેશભાઈ રોકડ",
    reporting_to: "બટુકભાઈ રાદડીયા",
    last_name: "Rokad",
    first_name: "Chandreshbhai",
    father_name: "Ramnikbhai",
    mobile: "9909428413",
    designation_gujarતી: "",
    active: "Y",
  },
  {
    id: 693,
    code: "N-B-Z18-V32-V32",
    group: "B",
    zone: "Z18",
    subzone1: "V32",
    subzone2: "V32",
    name_gujarati: "સંદિપભાઈ અંટાળા",
    role_gujarati: "વાહક",
    full_name_gujarati: "સંદિપભાઈ અંટાળા",
    reporting_to: "વિરલભાઈ અંટાળા",
    last_name: "Antala",
    first_name: "Sandeepbhai",
    father_name: "Kalubhai",
    mobile: "9099920156",
    designation_gujarતી: "",
    active: "Y",
  },
];
